Feature/overhaul interactive merge
raxod502/straight.el pull request #711
Opened 2021-03-07 04:10 UTC by pdbrown

Hi there, thanks for this package manager! It's great and has brought some sanity back to my Emacs config. I started using it a little while ago, and was recently been doing a bunch of package upgrades. I thought it might be cool if there were a way to pop up a log of exactly the commits an update would include, without firing up all of magit and having to see for myself. I started digging through the code to see what it would take to add this and I noticed a few things that seemed like they could be improved on, and after making a few notes, see here
https://github.com/pdbrown/straight.el/compare/scratch/interactive-merge%5E...scratch/interactive-merge
ended up overhauling a larger portion than I'd set out to.
In addition to a bit of rewriting, this change adds a new option during interactive updates:
```l --- Git log $COMMIT_RANGE and open recursive edit```
to pop up a git log buffer.

It also fixes a few related issues:

;; Rebase in progress
https://github.com/raxod502/straight.el/issues/271

;; Does not appear to handle detached head correctly
https://github.com/raxod502/straight.el/issues/194

;; Duplicate fast forward popup
https://github.com/raxod502/straight.el/issues/205

;; Ambiguous ref names
https://github.com/raxod502/straight.el/issues/306

2021-03-07 13:53 UTC, progfolio commented on straight.el
> +  "Ensure that DEFAULT-BRANCH is ahead of REMOTE-BRANCH in LOCAL-REPO.
CI is failing due to checkdoc complaining about the order of the arguments in the docstring.

```suggestion
  "Ensure LOCAL-REPO's DEFAULT-BRANCH is ahead of REMOTE-BRANCH.
```

2021-03-07 13:55 UTC, progfolio commented on straight.el
> +  "Show changelog buffer for RANGE of commits in LOCAL-REPO.
Same as above:

```suggestion
  "Show LOCAL-REPO's changelog buffer for RANGE of commits.
```

2021-03-07 14:15 UTC, progfolio commented on straight.el
> +  (let ((process-environment (append (list "LC_ALL=C") process-environment)))
If this pattern of overriding the locale is common enough, we could write a macro for it:
Something like the following should work:

```emacs-lisp
(defmacro straight-vc-git-with-locale (&rest body)
  "Execute BODY with user locale overridden."
  (declare (indent defun))
  `(let ((process-environment (append (list "LC_ALL=C") process-environment)))
     ,@body))
```

2021-03-07 15:35 UTC, progfolio commented on straight.el
> +    ;; stderr together, so we must parse the combined output instead.
Thank you for bringing this to my attention. I agree it would be useful to distinguish stderr from stdout. Working on a patch now.

2021-03-07 21:40 UTC, pdbrown commented on straight.el
> +  (let ((process-environment (append (list "LC_ALL=C") process-environment)))
Ah yeah, thanks for the heads up: I'd originally been parsing the warning message, but opted to look for any extra rev-parse output instead. I don't think we need to override the locale just to read ref names, so I got rid of these below.

2021-03-07 21:43 UTC, pdbrown commented on straight.el
> +    ;; stderr together, so we must parse the combined output instead.
Oh nice! I'd considered it briefly but this change had become big enough, so I went with the workaround for now.

2021-03-08 00:45 UTC, raxod502 commented on straight.el
> +    ;; stderr together, so we must parse the combined output instead.
Unfortunately, this might be harder than you think. I don't believe there's any non-hacky way to get stderr separately without migrating to the asynchronous process invocation API (`make-process`), and it turns out to be extremely tricky to just say "wait synchronously for the process to finish".

I've tried a number of times in https://github.com/raxod502/straight.el/issues/334.

2021-03-08 00:48 UTC, raxod502 commented
This is greatly appreciated and much-needed; a lot of that code is a bit of a mess :flushed: 
Thank you!

2021-03-08 18:39 UTC, pdbrown commented
Sure thing -- I'm happy to pitch in where helpful, and thanks for the reviews!

2021-03-09 13:51 UTC, progfolio commented
Should take care of #354,too

2021-03-09 22:11 UTC, progfolio commented on straight.el
> +    ;; stderr together, so we must parse the combined output instead.
The method I ended up implementing uses `call-process` synchronously. The `destination` argument may be a list, `(REAL-BUFFER STDERR-FILE)`. See: #714

2021-03-09 22:20 UTC, progfolio commented on straight.el
> +  ;; for exit status 0 and non-empty stderr to detect this case, but
psuedo-code illustration of what this would look like once #714 is merged:

```emacs-lisp
(straight--process-with-result
    (straight--process-run "git" "rev-parse" "--verify" ref)
  (if (and invoked stderr)
      (error "Failed to parse-rev %S\n%s" ref stderr)
    ;;happy case
    ))
```

2021-03-18 15:01 UTC, progfolio commented on straight.el
> +                         (straight--get-call "git" "rev-parse" "--git-dir")))))
#714 Has been merged into develop. You'll want to replace calls to `straight--get-call` with `straight--process-output`. The output will have the leading/trailing whitespace trimmed unless you bind `straight--process-trim` to nil. e.g. to get the old behavior of `straight--get-call-raw`:

```emacs-lisp
(let ((straight--process-trim nil))
  (straight--process-output "program" "arg"))
```

2021-03-18 15:03 UTC, progfolio commented on straight.el
> +  ;; for exit status 0 and non-empty stderr to detect this case, but
#714 merged. Should be able to distinguish stderr from stdout as noted in the previous comment.

2021-03-18 15:05 UTC, progfolio requested changes
You'll want to rebase your changes on top of the develop branch and replace any of the old process function calls with the new ones. If you any help or have any questions, let me know.
Thank you.

2021-04-02 05:11 UTC, pdbrown reviewed
Awesome! Thanks for the heads up and sorry about the delay, but here's an updated, squashed change.

2021-04-02 05:11 UTC, pdbrown commented on straight.el
> -              (gethash "magit" straight--profile-cache))
One thing to note here is that this `straight--profile-cache` lookup was in pretty old code and I couldn't tell what it was for: if the `require` fails, how would this help? I got rid of it in the new version, but can adjust it if I missed something.

2021-04-02 05:11 UTC, pdbrown commented on straight.el
> +                  (magit-log-setup-buffer (list range) args nil)
This is new since the last update, `magit-log` is pretty great!

2021-04-04 18:19 UTC, raxod502 commented on straight.el
> -              (gethash "magit" straight--profile-cache))
Great question. The intent was to see if the user had already pulled in Magit via `straight-use-package`, and so requesting it again would have no effect. Of course, as you observe, checking for this condition won't actually help anything, so I don't think there any reason to keep the check around. I couldn't tell you exactly what was going through my mind at the time.

2021-04-07 18:39 UTC, pdbrown commented
I rebased again to run with the new tests, and to fix the small merge conflict. I'd changed `(require 'cl-lib)` to `(require 'cl-macs)`, but reverted back to `cl-lib`, since that was/is working fine.

2021-04-07 18:55 UTC, progfolio approved these changes
Looks good to me. Thanks again for this!

2021-04-07 18:56 UTC, merged

2021-04-07 20:41 UTC, pdbrown commented
No problem and thanks again for all the reviews!